# Generated by Django 2.2.6 on 2022-03-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
